#!/usr/bin/env python

Import("env")
Import("env_modules")

env_cms_3d_extensions = env_modules.Clone()

env_cms_3d_extensions.add_source_files(env.modules_sources, "*.cpp")
env_cms_3d_extensions.add_source_files(env.modules_sources, "./scene/resources/3d/*.cpp")
