#!/usr/bin/env python

Import("env")
Import("env_modules")

env_data_table = env_modules.Clone()

env_data_table.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
	env_data_table.add_source_files(env.modules_sources, "./editor/*.cpp")
