#!/usr/bin/env python

Import("env")
Import("env_modules")

env_uniform_art = env_modules.Clone()

env_uniform_art.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
	env_uniform_art.add_source_files(env.modules_sources, "./editor/*.cpp")
	env_uniform_art.add_source_files(env.modules_sources, "./editor/plugins/*.cpp")
